package main

import(
	"fmt"
	"os"
	"net/http"
	"database/sql"
	"server_basics.com/middlewares"
	"server_basics.com/handlers"
	"server_basics.com/config"
	_ "github.com/lib/pq" //imported for side effects.
	"github.com/joho/godotenv"
	"server_basics.com/internal/database" // the db package generated by sqlc
)

func main(){

	err := godotenv.Load() //Loading envirement variable
	if err != nil {
		panic("Error loading .env file!!.")
	}

	dbURL := os.Getenv("DB_URL") //getting the DB_URL from .env 

	db, err := sql.Open("postgres", dbURL)//open connection to your dbQueries
	if err != nil {
		panic(err)
	}

	dbQueries := database.New(db)

	router := http.NewServeMux() //Http request multiplexer/router
	apiCfg := &config.ApiConfig{	
		Database: dbQueries, 
	}	
	// serving files from the current dir (index.html)
	router.Handle("/app/",http.StripPrefix("/app/", http.FileServer(http.Dir("."))))
	
	// we write the response to ResponseWriter.
	router.HandleFunc("GET /api/healthz",handlers.ServerHealthCheck) 
	router.HandleFunc("GET /admin/metrics",handlers.Metric(apiCfg)) //normal func & closure mechanism. 
	router.HandleFunc("POST /admin/reset",handlers.Reset(apiCfg))
	router.HandleFunc("POST /api/validate_chirp",handlers.ChirpValidator)

	handlerState := &handlers.ApiCfgState{
		DB: dbQueries, // This now works because DB is capitalized in user.go!
	} 
	router.HandleFunc("POST /api/users", handlerState.CreateUserHandler)
	
	port := "8080"
	server := &http.Server{
		Addr : ":"+port,
		Handler : router,
	}

	fmt.Println("The server is up & running on port"+server.Addr+"....")
	
 	err = http.ListenAndServe(server.Addr, 
		middleware.MiddlewareLog(
			middleware.MiddlewareMetricsInc(apiCfg, server.Handler), //wrapped the handler inside the count middlware.
	)) // logging every request handler using middlware.

	if err != nil {
		 fmt.Printf("Server connection failed %v", err)
	}
}
